language: python
python:
  - 3.6
install:
  - pip install codecov
env:
  - CODECOV_TOKEN="1f2406a0-ac7b-41b2-b93f-57eed633f2b7"
script:
  - ./setup.py test
after_success:
  - codecov -t $CODECOV_TOKEN

